# Site settings
author: Ifeoluwa  Akinremi-Wade
title: 
header-img: img/home-bg.png
email: ifeoluwa.wade@gmail.com
copyright_name: Ifeoluwa  Akinremi-Wade
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  IfeAkiWad

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
